---
- name: Insert docker mirror config in {{ podman_registry_config }}
  blockinfile:
    path: "{{ podman_registry_config }}"
    block: "{{ docker_registry_mirror }}"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "# insecure = true"
