---
- name: Insert docker mirror config in {{ podman_registry_config }}
  ansible.builtin.blockinfile:
    path: "{{ podman_registry_config }}"
    block: "{{ docker_registry_mirror }}"
    marker: "# added registry mirror w/ ansible"
    insertafter: "# insecure = true"
    backup: yes
