---
# tasks file for install-configure-podman
- name: Load os_family dependent variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install podman packages
  package:
    name: "{{ podman_packages }}"
    state: present
