---
# tasks file for install-configure-podman
- name: Load os_family dependent variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yaml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml'
      paths:
        - 'vars'

- name: Add podman/buildah repository key
  ansible.builtin.apt_key:
    url: "{{ podman_ppa_key }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Enable podman/buildah repository
  apt_repository:
    repo: "deb {{ podman_ppa_repo }}"
    update_cache: yes
    filename: buildah
  when: ansible_os_family == 'Debian'

- name: Install podman/buildah packages
  apt:
    name: "{{ podman_packages }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install podman packages
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present