---
- name: Load os_family dependent variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yaml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml'
      paths:
        - 'vars'

- name: Install debian prerequistes
  include: prerequisites-debian.yaml
  when: ansible_os_family == 'Debian' and not ansible_distribution_version == '22.04'

- name: Install podman packages
  include_role:
    name: install-requirements
  vars:
    update_packages: true
    remote_os_packages: "{{ podman_remote_packages | default(omit) }}"
    python_modules: "{{ podman_python_modules }}"
    os_packages: "{{ podman_os_packages }}"
  tags: setup

- name: Add docker registry mirror
  include: add-docker-mirror.yaml
  when: configure_docker_registry_mirror|bool
