---
# tasks file for install-configure-podman
- name: Load os_family dependent variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - '{{ ansible_os_family }}.yaml'
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml'
      paths:
        - 'vars'

- name: Add podman/buildah repository key
  ansible.builtin.apt_key:
    url: "{{ podman_ppa_key }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: Enable podman/buildah repository
  ansible.builtin.apt_repository:
    repo: "deb {{ podman_ppa_repo }}"
    update_cache: yes
    filename: buildah
  when: ansible_os_family == 'Debian'

- name: Update apt cache on Debian
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install python requirements
  include_role:
    name: install-requirements
  vars:
    update_packages: true
    remote_os_packages: "{{ podman_remote_os_package }}"
    python_modules: "{{ podman_python_modules }}"
    os_packages: "{{ podman_os_packages }}"
  tags: setup

- name: Install podman packages
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present